-- Script was generated by Devart dbForge Studio for MySQL, Version 4.50.285.0
-- Script date 03/05/2013 17:42:48
-- Server version: 5.1.39-community
-- Client version: 4.1

DROP DATABASE IF EXISTS intranet_ceti;
CREATE DATABASE IF NOT EXISTS intranet_ceti
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

USE intranet_ceti;

CREATE TABLE IF NOT EXISTS tbl_permission(
  id_permission INT(11) NOT NULL AUTO_INCREMENT,
  key_permission VARCHAR(255) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  valor TINYINT(4) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_permission),
  UNIQUE INDEX key_permission (key_permission)
)
ENGINE = INNODB
AUTO_INCREMENT = 14
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_role(
  id_role VARCHAR(255),
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_role)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_subject(
  id_subject INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_subject)
)
ENGINE = INNODB
AUTO_INCREMENT = 10
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_role_permission(
  id_role_permission INT(11) NOT NULL AUTO_INCREMENT,
  id_role VARCHAR(255) DEFAULT NULL,
  id_permission INT(11) DEFAULT NULL,
  valor TINYINT(4) DEFAULT 1,
  PRIMARY KEY (id_role_permission),
  INDEX FK_tlb_role_permission_tbl_permission_id_permission (id_permission),
  INDEX FK_tlb_role_permission_tbl_role_id_role (id_role),
  CONSTRAINT FK_tlb_role_permission_tbl_permission_id_permission FOREIGN KEY (id_permission)
  REFERENCES tbl_permission (id_permission),
  CONSTRAINT FK_tlb_role_permission_tbl_role_id_role FOREIGN KEY (id_role)
  REFERENCES tbl_role (id_role)
)
ENGINE = INNODB
AUTO_INCREMENT = 14
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_users(
  id_user INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  id_role VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_user),
  INDEX FK_tbl_user_tbl_role_id_role (id_role),
  CONSTRAINT FK_tbl_user_tbl_role_id_role FOREIGN KEY (id_role)
  REFERENCES tbl_role (id_role)
)
ENGINE = INNODB
AUTO_INCREMENT = 19
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_person(
  id_person INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  cellphone VARCHAR(255) DEFAULT NULL,
  dni VARCHAR(255) DEFAULT NULL,
  sex VARCHAR(255) DEFAULT NULL,
  `e-mail` VARCHAR(255) DEFAULT NULL,
  born VARCHAR(11) DEFAULT NULL,
  id_user INT(11) DEFAULT NULL,
  PRIMARY KEY (id_person),
  UNIQUE INDEX id_user (id_user),
  CONSTRAINT FK_tbl_person_tbl_users_id_user FOREIGN KEY (id_user)
  REFERENCES tbl_users (id_user)
)
ENGINE = INNODB
AUTO_INCREMENT = 19
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_alumn(
  id_alumn INT(11) NOT NULL AUTO_INCREMENT,
  id_person INT(11) DEFAULT NULL,
  `condition` VARCHAR(10) DEFAULT NULL,
  PRIMARY KEY (id_alumn),
  UNIQUE INDEX id_person (id_person),
  CONSTRAINT FK_tbl_alumn_tbl_person_id_person FOREIGN KEY (id_person)
  REFERENCES tbl_person (id_person)
)
ENGINE = INNODB
AUTO_INCREMENT = 14
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_docente(
  id_docente INT(11) NOT NULL AUTO_INCREMENT,
  id_person INT(11) DEFAULT NULL,
  PRIMARY KEY (id_docente),
  UNIQUE INDEX id_persona (id_person),
  CONSTRAINT FK_tbl_docente_tbl_person_id_person FOREIGN KEY (id_person)
  REFERENCES tbl_person (id_person)
)
ENGINE = INNODB
AUTO_INCREMENT = 5
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_registration(
  id_registration INT(11) NOT NULL,
  id_alumno INT(11) DEFAULT NULL,
  grade_section VARCHAR(4) DEFAULT NULL,
  `year` INT(4) DEFAULT NULL,
  id_docente INT(4) DEFAULT NULL,
  PRIMARY KEY (id_registration),
  INDEX FK_tbl_registration_tbl_alumn_id_alumn (id_alumno),
  INDEX FK_tbl_registration_tbl_docente_id_docente (id_docente),
  CONSTRAINT FK_tbl_registration_tbl_alumn_id_alumn FOREIGN KEY (id_alumno)
  REFERENCES tbl_alumn (id_alumn),
  CONSTRAINT FK_tbl_registration_tbl_docente_id_docente FOREIGN KEY (id_docente)
  REFERENCES tbl_docente (id_docente)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS tbl_record(
  id_bimester INT(11) NOT NULL AUTO_INCREMENT,
  id_subject INT(3) DEFAULT NULL,
  N1_average DOUBLE DEFAULT NULL,
  N2_average DOUBLE DEFAULT NULL,
  N3_average DOUBLE DEFAULT NULL,
  N4_average DOUBLE DEFAULT NULL,
  id_registration INT(11) DEFAULT NULL,
  PRIMARY KEY (id_bimester),
  INDEX FK_tbl_bimester_tbl_subject_id_subject (id_subject),
  INDEX FK_tbl_record_tbl_registration_id_registration (id_registration),
  CONSTRAINT FK_tbl_record_tbl_registration_id_registration FOREIGN KEY (id_registration)
  REFERENCES tbl_registration (id_registration),
  CONSTRAINT FK_tbl_record_tbl_subject_id_subject FOREIGN KEY (id_subject)
  REFERENCES tbl_subject (id_subject)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;