-- Script was generated by Devart dbForge Studio for MySQL, Version 4.50.285.0
-- Script date 24/04/2013 20:13:10
-- Server version: 5.5.20-log
-- Client version: 4.1

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Definition for database intranet_ceti
--
DROP DATABASE IF EXISTS intranet_ceti;
CREATE DATABASE intranet_ceti
	CHARACTER SET latin1
	COLLATE latin1_swedish_ci;

-- 
-- Set default database
--
USE intranet_ceti;

--
-- Definition for table tbl_alumn
--
CREATE TABLE tbl_alumn (
  id_alumn INT(11) NOT NULL AUTO_INCREMENT,
  id_person INT(11) DEFAULT NULL,
  id_rol VARCHAR(255) DEFAULT NULL,
  grade INT(11) DEFAULT NULL,
  section VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_alumn),
  UNIQUE INDEX id_person (id_person)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_course
--
CREATE TABLE tbl_course (
  id_course VARCHAR(255),
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_course)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_docente
--
CREATE TABLE tbl_docente (
  id_docente INT(11) NOT NULL AUTO_INCREMENT,
  id_curso VARCHAR(255) DEFAULT NULL,
  id_persona INT(11) DEFAULT NULL,
  PRIMARY KEY (id_docente),
  UNIQUE INDEX id_persona (id_persona)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_permission
--
CREATE TABLE tbl_permission (
  id_permission INT(11) NOT NULL AUTO_INCREMENT,
  name VARCHAR(255) DEFAULT NULL,
  description TEXT DEFAULT NULL,
  PRIMARY KEY (id_permission)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_record
--
CREATE TABLE tbl_record (
  id_record INT(11) NOT NULL AUTO_INCREMENT,
  id_alumno INT(11) DEFAULT NULL,
  id_grade INT(11) DEFAULT NULL,
  id_section INT(11) DEFAULT NULL,
  id_curso VARCHAR(255) DEFAULT NULL,
  nota_final INT(11) DEFAULT NULL,
  PRIMARY KEY (id_record),
  INDEX FK_tbl_record_tbl_alumn_id_alumn (id_alumno)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_role
--
CREATE TABLE tbl_role (
  id_role VARCHAR(255),
  name VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_role)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_docente_curso
--
CREATE TABLE tbl_docente_curso (
  id_docente_curso VARCHAR(255),
  id_docente INT(11) DEFAULT NULL,
  id_curso VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_docente_curso),
  INDEX FK_tbl_docente_curso_tbl_course_id_course (id_curso),
  INDEX FK_tbl_docente_curso_tbl_docente_id_docente (id_docente),
  CONSTRAINT FK_tbl_docente_curso_tbl_course_id_course FOREIGN KEY (id_curso)
    REFERENCES tbl_course(id_course),
  CONSTRAINT FK_tbl_docente_curso_tbl_docente_id_docente FOREIGN KEY (id_docente)
    REFERENCES tbl_docente(id_docente)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_person
--
CREATE TABLE tbl_person (
  id_person INT(11) NOT NULL,
  name VARCHAR(255) DEFAULT NULL,
  lastname VARCHAR(255) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  phone VARCHAR(255) DEFAULT NULL,
  cellphone VARCHAR(255) DEFAULT NULL,
  dni VARCHAR(255) DEFAULT NULL,
  sex VARCHAR(255) DEFAULT NULL,
  `e-mail` VARCHAR(255) DEFAULT NULL,
  id_user INT(11) DEFAULT NULL,
  PRIMARY KEY (id_person),
  UNIQUE INDEX id_user (id_user),
  CONSTRAINT FK_tbl_person_tbl_alumn_id_person FOREIGN KEY (id_person)
    REFERENCES tbl_alumn(id_person),
  CONSTRAINT FK_tbl_person_tbl_docente_id_persona FOREIGN KEY (id_person)
    REFERENCES tbl_docente(id_persona)
)
ENGINE = INNODB
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tlb_role_permission
--
CREATE TABLE tlb_role_permission (
  id_role_permission INT(11) NOT NULL AUTO_INCREMENT,
  id_role VARCHAR(255) DEFAULT NULL,
  id_permission INT(11) DEFAULT NULL,
  PRIMARY KEY (id_role_permission),
  INDEX FK_tlb_role_permission_tbl_permission_id_permission (id_permission),
  INDEX FK_tlb_role_permission_tbl_role_id_role (id_role),
  CONSTRAINT FK_tlb_role_permission_tbl_permission_id_permission FOREIGN KEY (id_permission)
    REFERENCES tbl_permission(id_permission),
  CONSTRAINT FK_tlb_role_permission_tbl_role_id_role FOREIGN KEY (id_role)
    REFERENCES tbl_role(id_role)
)
ENGINE = INNODB
AUTO_INCREMENT = 1
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

--
-- Definition for table tbl_user
--
CREATE TABLE tbl_user (
  id_user INT(11) NOT NULL AUTO_INCREMENT,
  email VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  id_role VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id_user),
  INDEX FK_tbl_user_tbl_role_id_role (id_role),
  CONSTRAINT FK_tbl_user_tbl_person_id_user FOREIGN KEY (id_user)
    REFERENCES tbl_person(id_user),
  CONSTRAINT FK_tbl_user_tbl_role_id_role FOREIGN KEY (id_role)
    REFERENCES tbl_role(id_role)
)
ENGINE = INNODB
AUTO_INCREMENT = 2
CHARACTER SET latin1
COLLATE latin1_swedish_ci;

-- 
-- Dumping data for table tbl_alumn
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_course
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_docente
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_permission
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_record
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_role
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_docente_curso
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_person
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tlb_role_permission
--
-- Table does not contain any data (it is empty)

-- 
-- Dumping data for table tbl_user
--
-- Table does not contain any data (it is empty)

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;